=== Ghostrecon88/baseline-codebase/src/rex.instrument/src/rex/instrument/schemas/instrument.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "id": "http://rexdb.com/instrument/0.7.0#",
    "title": "Common Instrument Definition",

    "definitions": {
        "identifierType": {
            "type": "string",

            "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
        },

        "simpleDataType": {
            "enum": [
                "float",
                "integer",
                "text",
                "enumeration",
                "enumerationSet",
                "boolean",
                "date",
                "time",
                "dateTime"
            ]
        },

        "complexDataType": {
            "enum": [
                "recordList",
                "matrix"
            ]
        },

        "standardDataType": {
            "oneOf": [
                { "$ref": "#definitions/simpleDataType" },
                { "$ref": "#definitions/complexDataType" }
            ]
        },

        "customDataType": {
            "type": "string",

            "pattern": "^(?!(text|integer|float|boolean|enumeration|enumerationSet|date|time|dateTime|recordList|matrix)$)[a-zA-Z0-9_]+[a-zA-Z0-9]$"
        },

        "requiredOptionalType": {
            "enum": [
                "required",
                "optional",
                "none"
            ]
        },

        "timeBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "dateBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "dateTimeBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])T(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])T(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "numericBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "number"
                },

                "max": {
                    "type": "number"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "enumerationType": {
            "type": "object",

            "properties": {
                "description": {
                    "type": "string"
                }
            },

            "additionalProperties": false
        },

        "fieldType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "type": {
                    "oneOf": [
                        { "$ref": "#/definitions/typeDefinitionType" },
                        { "$ref": "#/definitions/simpleDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "required": {
                    "type": "boolean"
                },

                "annotation": {
                    "$ref": "#definitions/requiredOptionalType"
                },

                "explanation": {
                    "$ref": "#definitions/requiredOptionalType"
                },

                "identifiable": {
                    "type": "boolean"
                }
            },

            "required": [
                "id",
                "type"
            ],

            "additionalProperties": false
        },

        "recordType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/fieldType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "rowType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "required": {
                    "type": "boolean"
                }
            },

            "required": [
                "id"
            ],

            "additionalProperties": false
        },

        "rowListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/rowType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "columnType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "type": {
                    "oneOf": [
                        { "$ref": "#/definitions/typeDefinitionType" },
                        { "$ref": "#/definitions/simpleDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "required": {
                    "type": "boolean"
                },

                "identifiable": {
                    "type": "boolean"
                }
            },

            "required": [
                "id",
                "type"
            ],

            "additionalProperties": false
        },

        "columnListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/columnType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "typeDefinitionType": {
            "type": "object",

            "properties": {
                "base": {
                    "oneOf": [
                        { "$ref": "#/definitions/standardDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "range": {
                    "oneOf": [
                        { "$ref": "#/definitions/numericBoundConstraintType" },
                        { "$ref": "#/definitions/dateBoundConstraintType" },
                        { "$ref": "#/definitions/timeBoundConstraintType" },
                        { "$ref": "#/definitions/dateTimeBoundConstraintType" }
                    ]
                },

                "length": {
                    "$ref": "#/definitions/numericBoundConstraintType"
                },

                "pattern": {
                    "type": "string",
                    "minLength": 1
                },

                "enumerations": {
                    "type": "object",

                    "patternProperties": {
                        "^(?:[a-z0-9]{1,2}|[a-z0-9](?:[a-z0-9]|[_-](?![_-]))+[a-z0-9])$": {
                            "oneOf": [
                                { "$ref": "#/definitions/enumerationType" },
                                { "type": "null" }
                            ]
                        }
                    },

                    "minProperties": 1,

                    "additionalProperties": false
                },

                "record": {
                    "$ref": "#/definitions/recordType"
                },

                "columns": {
                    "$ref": "#/definitions/columnListType"
                },

                "rows": {
                    "$ref": "#/definitions/rowListType"
                }
            },

            "required": [
                "base"
            ],

            "additionalProperties": false
        },

        "typeCollectionType": {
            "type": "object",

            "patternProperties": {
                "^(?!(text|integer|float|boolean|enumeration|enumerationSet|date|time|dateTime|recordList|matrix)$)[a-zA-Z0-9_]+[a-zA-Z0-9]$": {
                    "$ref": "#/definitions/typeDefinitionType"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        }
    },

    "type": "object",

    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        },

        "version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+$"
        },

        "title": {
            "type": "string",
            "minLength": 1
        },

        "description": {
            "type": "string"
        },

        "types": {
            "$ref": "#/definitions/typeCollectionType"
        },

        "record": {
            "$ref": "#/definitions/recordType"
        }
    },

    "required": [
        "id",
        "version",
        "title",
        "record"
    ],

    "additionalProperties": false
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/instruments/recordlist_complex_field.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
            "id": "q_fake",
            "type": {
                "base": "recordList",
                "record": [
                    {
                        "id": "quest1",
                        "type": "text"
                    },
                    {
                        "id": "quest2",
                        "type": {
                            "base": "recordList",
                            "record": [
                                {
                                    "id": "foobar",
                                    "type": "text"
                                }
                            ]
                        }
                    }
                ]
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/js/rex-formbuilder/test/definitions/parse-radiobuttongroup-instrument.json
{
  "id": "urn:test-instrument",
  "version": "1.1",
  "title": "The Instrument Title",
  "record": [
    {
      "id": "q_fake",
      "type": {
        "base": "enumeration",
        "enumerations": {
          "foo": {},
          "bar": {}
        }
      }
    },
    {
      "id": "q_fake2",
      "type": {
        "base": "enumeration",
        "enumerations": {
          "foo": {},
          "bar": {}
        }
      }
    },
    {
      "id": "q_fake3",
      "type": {
        "base": "enumeration",
        "enumerations": {
          "foo": {},
          "bar": {}
        }
      }
    },
    {
      "id": "q_fake4",
      "type": {
        "base": "enumeration",
        "enumerations": {
          "foo": {},
          "bar": {}
        }
      }
    },
    {
      "id": "q_fake5",
      "type": {
        "base": "enumeration",
        "enumerations": {
          "foo": {},
          "bar": {}
        }
      }
    },
    {
      "id": "q_fake6",
      "type": {
        "base": "enumeration",
        "enumerations": {
          "foo": {},
          "bar": {}
        }
      }
    },
    {
      "id": "q_fake7",
      "type": {
        "base": "enumeration",
        "enumerations": {
          "foo": {},
          "bar": {}
        }
      }
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/static/examples/simple/instrument.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The Simple Instrument",
    "record": [
        {
            "id": "q_name",
            "type": "text",
            "required": false,
            "annotation": "optional"
        },
        {
            "id": "q_age",
            "type": "integer",
            "required": false,
            "annotation": "required"
        },
        {
            "id": "q_color",
            "type": "text",
            "explanation": "optional"
        },


        {
            "id": "q_city",
            "type": "text",
            "required": true,
            "explanation": "required"
        },
        {
            "id": "q_country",
            "type": "text",
            "required": true
        },
        {
            "id": "q_car",
            "type": "text",
            "required": true
        },


        {
            "id": "q_place",
            "type": "text",
            "required": true
        },
        {
            "id": "q_something",
            "type": "text",
            "required": true
        },
        {
            "id": "q_anotherthing",
            "type": "text",
            "required": true
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/instruments/matrix_complex_column.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
            "id": "q_fake",
            "type": {
                "base": "matrix",
                "columns": [
                    {
                        "id": "blah",
                        "type": "text",
                        "required": true
                    },
                    {
                        "id": "foobar",
                        "type": {
                            "base": "recordList",
                            "record": [
                                {
                                    "id": "baz",
                                    "type": "text"
                                }
                            ]
                        }
                    }
                ],
                "rows": [
                    {
                        "id": "somerow",
                        "required": true
                    }
                ]
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/instruments/calculation.json
{
    "id": "urn:test-calculation",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
          "id": "age",
          "type": {
            "base": "enumeration",
            "enumerations": {
              "age30-49": {},
              "age50-64": {},
              "age65-and-over": {},
              "age18-29": {}
            }
          }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/test/forms/instruments/constraint_enumerations_numeric.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "Some Enumerations",
    "record": [
        {
            "id": "q_enumeration",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "1": {},
                    "0": {},
                    "2": {}
                }
            }
        },
        {
            "id": "q_enumerationset",
            "type": {
                "base": "enumerationSet",
                "enumerations": {
                    "1": {},
                    "0": {},
                    "2": {}
                }
            }
        },
        {
            "id": "q_enumeration2",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "foo": {},
                    "bar": {},
                    "1": {}
                }
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.formbuilder/static/js/test/definitions/parse-repeatinggroup-instrument.json
{
  "id": "urn:test-instrument",
  "version": "1.1",
  "title": "The InstrumentVersion Title",
  "record": [
    {
      "id": "q_fake",
      "type": {
        "base": "recordList",
        "record": [
          {
            "id": "quest1",
            "type": "text"
          },
          {
            "id": "quest2",
            "type": "integer"
          }
        ]
      }
    },
    {
      "id": "q_fake2",
      "type": {
        "base": "recordList",
        "record": [
          {
            "id": "quest21",
            "type": "text"
          },
          {
            "id": "quest22",
            "type": "integer"
          }
        ]
      }
    },
    {
      "id": "q_fake3",
      "type": {
        "base": "recordList",
        "record": [
          {
            "id": "quest31",
            "type": {
              "base": "text",
              "pattern": "foo"
            }
          },
          {
            "id": "quest32",
            "type": "integer"
          }
        ],
        "length": {
          "max": 5
        }
      }
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.deploy/demo/static/deploy/demographics-form-instrument.json
{
    "id": "urn:demographics-form",
    "version": "1.0",
    "title": "Demo Demographic Form",
    "record": [
        {
            "id": "first_name",
            "type": "text"
        },
        {
            "id": "last_name",
            "type": "text"
        },
        {
            "id": "gender",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "male": {},
                    "female": {}
                }
            }
        },
        {
            "id": "age",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "age18-29": {},
                    "age30-49": {},
                    "age50-64": {},
                    "age65-and-over": {}
                }
            }
        },
        {
            "id": "education",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "less-than-hs": {},
                    "hs-grad": {},
                    "bachelor-degree": {},
                    "post-graduate-degree": {}
                }
            }
        },
        {
            "id": "ethnicity",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "white": {},
                    "hispanic": {},
                    "african-american": {},
                    "native-american": {},
                    "asian": {},
                    "other": {}
                }
            }
        },
        {
            "id": "employment",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "full-time": {},
                    "part-time": {},
                    "unemployed": {},
                    "student": {},
                    "homemaker": {},
                    "retired": {}
                }
            }
        },
        {
            "id": "marital_status",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "single": {},
                    "married": {},
                    "widowed": {},
                    "divorced": {},
                    "separated": {}
                }
            }
        },
        {
            "id": "children",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "yes": {},
                    "no": {}
                }
            }
        },
        {
            "id": "number_of_children",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "one": {},
                    "two": {},
                    "three": {},
                    "four": {},
                    "five-or-more": {}
                }
            }
        }
    ]
}
