=== Ghostrecon88/baseline-codebase/src/rex.instrument/src/rex/instrument/schemas/instrument.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "id": "http://rexdb.com/instrument/0.7.0#",
    "title": "Common Instrument Definition",

    "definitions": {
        "identifierType": {
            "type": "string",

            "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
        },

        "simpleDataType": {
            "enum": [
                "float",
                "integer",
                "text",
                "enumeration",
                "enumerationSet",
                "boolean",
                "date",
                "time",
                "dateTime"
            ]
        },

        "complexDataType": {
            "enum": [
                "recordList",
                "matrix"
            ]
        },

        "standardDataType": {
            "oneOf": [
                { "$ref": "#definitions/simpleDataType" },
                { "$ref": "#definitions/complexDataType" }
            ]
        },

        "customDataType": {
            "type": "string",

            "pattern": "^(?!(text|integer|float|boolean|enumeration|enumerationSet|date|time|dateTime|recordList|matrix)$)[a-zA-Z0-9_]+[a-zA-Z0-9]$"
        },

        "requiredOptionalType": {
            "enum": [
                "required",
                "optional",
                "none"
            ]
        },

        "timeBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "dateBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "dateTimeBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])T(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])T(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "numericBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "number"
                },

                "max": {
                    "type": "number"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "enumerationType": {
            "type": "object",

            "properties": {
                "description": {
                    "type": "string"
                }
            },

            "additionalProperties": false
        },

        "fieldType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "type": {
                    "oneOf": [
                        { "$ref": "#/definitions/typeDefinitionType" },
                        { "$ref": "#/definitions/simpleDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "required": {
                    "type": "boolean"
                },

                "annotation": {
                    "$ref": "#definitions/requiredOptionalType"
                },

                "explanation": {
                    "$ref": "#definitions/requiredOptionalType"
                },

                "identifiable": {
                    "type": "boolean"
                }
            },

            "required": [
                "id",
                "type"
            ],

            "additionalProperties": false
        },

        "recordType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/fieldType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "rowType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "required": {
                    "type": "boolean"
                }
            },

            "required": [
                "id"
            ],

            "additionalProperties": false
        },

        "rowListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/rowType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "columnType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "type": {
                    "oneOf": [
                        { "$ref": "#/definitions/typeDefinitionType" },
                        { "$ref": "#/definitions/simpleDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "required": {
                    "type": "boolean"
                },

                "identifiable": {
                    "type": "boolean"
                }
            },

            "required": [
                "id",
                "type"
            ],

            "additionalProperties": false
        },

        "columnListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/columnType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "typeDefinitionType": {
            "type": "object",

            "properties": {
                "base": {
                    "oneOf": [
                        { "$ref": "#/definitions/standardDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "range": {
                    "oneOf": [
                        { "$ref": "#/definitions/numericBoundConstraintType" },
                        { "$ref": "#/definitions/dateBoundConstraintType" },
                        { "$ref": "#/definitions/timeBoundConstraintType" },
                        { "$ref": "#/definitions/dateTimeBoundConstraintType" }
                    ]
                },

                "length": {
                    "$ref": "#/definitions/numericBoundConstraintType"
                },

                "pattern": {
                    "type": "string",
                    "minLength": 1
                },

                "enumerations": {
                    "type": "object",

                    "patternProperties": {
                        "^(?:[a-z0-9]{1,2}|[a-z0-9](?:[a-z0-9]|[_-](?![_-]))+[a-z0-9])$": {
                            "oneOf": [
                                { "$ref": "#/definitions/enumerationType" },
                                { "type": "null" }
                            ]
                        }
                    },

                    "minProperties": 1,

                    "additionalProperties": false
                },

                "record": {
                    "$ref": "#/definitions/recordType"
                },

                "columns": {
                    "$ref": "#/definitions/columnListType"
                },

                "rows": {
                    "$ref": "#/definitions/rowListType"
                }
            },

            "required": [
                "base"
            ],

            "additionalProperties": false
        },

        "typeCollectionType": {
            "type": "object",

            "patternProperties": {
                "^(?!(text|integer|float|boolean|enumeration|enumerationSet|date|time|dateTime|recordList|matrix)$)[a-zA-Z0-9_]+[a-zA-Z0-9]$": {
                    "$ref": "#/definitions/typeDefinitionType"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        }
    },

    "type": "object",

    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        },

        "version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+$"
        },

        "title": {
            "type": "string",
            "minLength": 1
        },

        "description": {
            "type": "string"
        },

        "types": {
            "$ref": "#/definitions/typeCollectionType"
        },

        "record": {
            "$ref": "#/definitions/recordType"
        }
    },

    "required": [
        "id",
        "version",
        "title",
        "record"
    ],

    "additionalProperties": false
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/instruments/repeated_id_matrix_row.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
            "id": "q_fake",
            "type": "text"
        },
        {
            "id": "q_foo",
            "type": {
                "base": "matrix",
                "columns": [
                    {
                        "id": "q_fake",
                        "type": "text",
                        "required": true
                    },
                    {
                        "id": "foobar",
                        "type": {
                            "base": "integer",
                            "range": { "min": 10 }
                        }
                    }
                ],
                "rows": [
                    {
                        "id": "somerow",
                        "required": true
                    }
                ]
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/assessments/custom_type/instrument.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "types": {
        "colors": {
            "base": "enumeration",
            "enumerations": {
                "red": {},
                "blue": {},
                "green": {}
            }
        }
    },
    "record": [
        {
            "id": "q_fake",
            "type": "colors"
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.formbuilder/js/test/definitions/parse-time-instrument.json
{
  "id": "urn:test-instrument",
  "version": "1.1",
  "title": "The Instrument Title",
  "record": [
    {
      "id": "q_fake",
      "type": "time"
    },
    {
      "id": "q_fake2",
      "type": "time"
    },
    {
      "id": "q_fake3",
      "type": {
        "base": "time",
        "range": {
          "max": "12:34:56"
        }
      }
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/assessments/all_types/instrument.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "My Instrument",

    "record": [
        {
            "id": "q_integer",
            "type": "integer"
        },
        {
            "id": "q_float",
            "type": "float"
        },
        {
            "id": "q_text",
            "type": "text"
        },
        {
            "id": "q_enumeration",
            "type": {
                "base": "enumeration",
                "enumerations": {
                  "myenum": {},
                  "other": {}
                }
            }
        },
        {
            "id": "q_enumerationset",
            "type": {
                "base": "enumerationSet",
                "enumerations": {
                  "myenum": {},
                  "other": {}
                }
            }
        },
        {
            "id": "q_boolean",
            "type": "boolean"
        },
        {
            "id": "q_date",
            "type": "date"
        },
        {
            "id": "q_datetime",
            "type": "dateTime"
        },
        {
            "id": "q_time",
            "type": "time"
        },
        {
            "id": "q_recordlist",
            "type": {
                "base": "recordList",
                "record": [
                    {
                        "id": "hello",
                        "type": "text"
                    },
                    {
                        "id": "goodbye",
                        "type": "text"
                    }
                ]
            }
        },
        {
            "id": "q_matrix",
            "type": {
                "base": "matrix",
                "columns": [
                    {
                        "id": "column1",
                        "type": "integer"
                    },
                    {
                        "id": "column2",
                        "type": "text"
                    }
                ],
                "rows": [
                    {
                        "id": "row1"
                    },
                    {
                        "id": "row2"
                    }
                ]
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.formbuilder/static/js/test/definitions/parse-date-instrument.json
{
  "id": "urn:test-instrument",
  "version": "1.1",
  "title": "The Instrument Title",
  "record": [
    {
      "id": "q_fake",
      "type": "date"
    },
    {
      "id": "q_fake2",
      "type": "date"
    },
    {
      "id": "q_fake3",
      "type": {
        "base": "date",
        "range": {
          "max": "2014-01-01"
        }
      }
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/instruments/identifiable_matrix.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
            "id": "q_fake",
            "type": {
                "base": "matrix",
                "columns": [
                    {
                        "id": "blah",
                        "type": "text",
                        "required": true,
                        "identifiable": true
                    },
                    {
                        "id": "foobar",
                        "type": {
                            "base": "integer",
                            "range": { "min": 10 }
                        },
                        "identifiable": false
                    }
                ],
                "rows": [
                    {
                        "id": "somerow",
                        "required": true
                    }
                ]
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.formbuilder/static/js/test/definitions/parse-float-instrument.json
{
  "id": "urn:test-instrument",
  "version": "1.1",
  "title": "The Instrument Title",
  "record": [
    {
      "id": "q_fake",
      "type": "float"
    },
    {
      "id": "q_fake2",
      "type": "float"
    },
    {
      "id": "q_fake3",
      "type": {
        "base": "float",
        "range": {
          "max": 20
        }
      }
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/instruments/repeated_id_matrix.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
            "id": "qq_fake",
            "type": "text"
        },
        {
            "id": "qq_foo",
            "type": {
                "base": "matrix",
                "columns": [
                    {
                        "id": "fake",
                        "type": "text",
                        "required": true
                    },
                    {
                        "id": "foobar",
                        "type": {
                            "base": "integer",
                            "range": { "min": 10 }
                        }
                    }
                ],
                "rows": [
                    {
                        "id": "qq",
                        "required": true
                    }
                ]
            }
        }
    ]
}
