=== Ghostrecon88/baseline-codebase/src/rex.instrument/src/rex/instrument/schemas/instrument.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "id": "http://rexdb.com/instrument/0.7.0#",
    "title": "Common Instrument Definition",

    "definitions": {
        "identifierType": {
            "type": "string",

            "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
        },

        "simpleDataType": {
            "enum": [
                "float",
                "integer",
                "text",
                "enumeration",
                "enumerationSet",
                "boolean",
                "date",
                "time",
                "dateTime"
            ]
        },

        "complexDataType": {
            "enum": [
                "recordList",
                "matrix"
            ]
        },

        "standardDataType": {
            "oneOf": [
                { "$ref": "#definitions/simpleDataType" },
                { "$ref": "#definitions/complexDataType" }
            ]
        },

        "customDataType": {
            "type": "string",

            "pattern": "^(?!(text|integer|float|boolean|enumeration|enumerationSet|date|time|dateTime|recordList|matrix)$)[a-zA-Z0-9_]+[a-zA-Z0-9]$"
        },

        "requiredOptionalType": {
            "enum": [
                "required",
                "optional",
                "none"
            ]
        },

        "timeBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "dateBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "dateTimeBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])T(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                },

                "max": {
                    "type": "string",
                    "pattern": "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:[0-2][0-9]|3[0-1])T(?:[0-1][0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])$"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "numericBoundConstraintType": {
            "type": "object",

            "properties": {
                "min": {
                    "type": "number"
                },

                "max": {
                    "type": "number"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "enumerationType": {
            "type": "object",

            "properties": {
                "description": {
                    "type": "string"
                }
            },

            "additionalProperties": false
        },

        "fieldType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "type": {
                    "oneOf": [
                        { "$ref": "#/definitions/typeDefinitionType" },
                        { "$ref": "#/definitions/simpleDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "required": {
                    "type": "boolean"
                },

                "annotation": {
                    "$ref": "#definitions/requiredOptionalType"
                },

                "explanation": {
                    "$ref": "#definitions/requiredOptionalType"
                },

                "identifiable": {
                    "type": "boolean"
                }
            },

            "required": [
                "id",
                "type"
            ],

            "additionalProperties": false
        },

        "recordType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/fieldType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "rowType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "required": {
                    "type": "boolean"
                }
            },

            "required": [
                "id"
            ],

            "additionalProperties": false
        },

        "rowListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/rowType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "columnType": {
            "type": "object",

            "properties": {
                "id": {
                    "$ref": "#definitions/identifierType"
                },

                "description": {
                    "type": "string"
                },

                "type": {
                    "oneOf": [
                        { "$ref": "#/definitions/typeDefinitionType" },
                        { "$ref": "#/definitions/simpleDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "required": {
                    "type": "boolean"
                },

                "identifiable": {
                    "type": "boolean"
                }
            },

            "required": [
                "id",
                "type"
            ],

            "additionalProperties": false
        },

        "columnListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/columnType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "typeDefinitionType": {
            "type": "object",

            "properties": {
                "base": {
                    "oneOf": [
                        { "$ref": "#/definitions/standardDataType" },
                        { "$ref": "#/definitions/customDataType" }
                    ]
                },

                "range": {
                    "oneOf": [
                        { "$ref": "#/definitions/numericBoundConstraintType" },
                        { "$ref": "#/definitions/dateBoundConstraintType" },
                        { "$ref": "#/definitions/timeBoundConstraintType" },
                        { "$ref": "#/definitions/dateTimeBoundConstraintType" }
                    ]
                },

                "length": {
                    "$ref": "#/definitions/numericBoundConstraintType"
                },

                "pattern": {
                    "type": "string",
                    "minLength": 1
                },

                "enumerations": {
                    "type": "object",

                    "patternProperties": {
                        "^(?:[a-z0-9]{1,2}|[a-z0-9](?:[a-z0-9]|[_-](?![_-]))+[a-z0-9])$": {
                            "oneOf": [
                                { "$ref": "#/definitions/enumerationType" },
                                { "type": "null" }
                            ]
                        }
                    },

                    "minProperties": 1,

                    "additionalProperties": false
                },

                "record": {
                    "$ref": "#/definitions/recordType"
                },

                "columns": {
                    "$ref": "#/definitions/columnListType"
                },

                "rows": {
                    "$ref": "#/definitions/rowListType"
                }
            },

            "required": [
                "base"
            ],

            "additionalProperties": false
        },

        "typeCollectionType": {
            "type": "object",

            "patternProperties": {
                "^(?!(text|integer|float|boolean|enumeration|enumerationSet|date|time|dateTime|recordList|matrix)$)[a-zA-Z0-9_]+[a-zA-Z0-9]$": {
                    "$ref": "#/definitions/typeDefinitionType"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        }
    },

    "type": "object",

    "properties": {
        "id": {
            "type": "string",
            "format": "uri"
        },

        "version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+$"
        },

        "title": {
            "type": "string",
            "minLength": 1
        },

        "description": {
            "type": "string"
        },

        "types": {
            "$ref": "#/definitions/typeCollectionType"
        },

        "record": {
            "$ref": "#/definitions/recordType"
        }
    },

    "required": [
        "id",
        "version",
        "title",
        "record"
    ],

    "additionalProperties": false
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/assessments/boolean/instrument.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
            "id": "q_fake",
            "type": "boolean",
            "required": true
        },
        {
            "id": "q_fake2",
            "type": "boolean",
            "required": false
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/instruments/repeated_id_record.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
            "id": "q_fake",
            "type": "text"
        },
        {
            "id": "q_foo",
            "type": {
                "base": "recordList",
                "record": [
                    {
                        "id": "q_fake",
                        "type": "integer"
                    }
                ]
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/static/js/example/specs/forms/localization/instrument.json
{
  "id": "urn:localization",
  "version": "1.0",
  "title": "Localization",
  "record": [
    {
      "id": "q1",
      "type": "text"
    },
    {
      "id": "q2",
      "type": "text"
    },
    {
      "id": "q3",
      "type": "integer"
    },
    {
      "id": "q4",
      "type": {
        "base": "enumeration",
        "enumerations": {
          "red": null,
          "blue": null,
          "green": null
        }
      }
    },
    {
      "id": "q5",
      "type": {
        "base": "matrix",
        "rows": [
          {
            "id": "row1"
          },
          {
            "id": "row2"
          }
        ],
        "columns": [
          {
            "id": "col1",
            "type": "text"
          },
          {
            "id": "col2",
            "type": "integer"
          }
        ]
      }
    },
    {
      "id": "q6",
      "type": {
        "base": "recordList",
        "record": [
          {
            "id": "subfield1",
            "type": "text"
          },
          {
            "id": "subfield2",
            "type": "integer"
          }
        ]
      }
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/static/js/example/specs/reconciliations/matrix/instrument.json
{
  "id": "urn:matrix",
  "version": "1.0",
  "title": "Matrix Reconciliation",
  "record": [
    {
      "id": "foo",
      "type": {
        "base": "matrix",
        "rows": [
          {
            "id": "row1"
          },
          {
            "id": "row2"
          }
        ],
        "columns": [
          {
            "id": "col1",
            "type": "text"
          },
          {
            "id": "col2",
            "type": "integer"
          }
        ]
      }
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/static/js/example/specs/reconciliations/recordlist/instrument.json
{
  "id": "urn:recordlist",
  "version": "1.0",
  "title": "RecordList Reconciliation",
  "record": [
    {
      "id": "foo",
      "type": {
        "base": "recordList",
        "record": [
          {
            "id": "subfield1",
            "type": "text"
          },
          {
            "id": "subfield2",
            "type": "integer"
          }
        ]
      }
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.instrument/test/instruments/constraint_enumerations_null.json
{
    "id": "urn:test-instrument",
    "version": "1.1",
    "title": "The InstrumentVersion Title",
    "record": [
        {
            "id": "q_enumeration",
            "type": {
                "base": "enumeration",
                "enumerations": {
                    "foo": {
                        "description": "Foo!"
                    }
                }
            }
        },
        {
            "id": "q_enumerationset",
            "type": {
                "base": "enumerationSet",
                "enumerations": {
                    "foo": {},
                    "bar": null
                }
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/rex.forms_demo/static/examples/recordlist/instrument.json
{
    "id": "urn:instrument",
    "version": "1.1",
    "title": "The Simple Instrument",
    "record": [
        {
            "id": "q_list",
            "type": {
                "base": "recordList",
                "record": [
                    {
                        "id": "q_thing",
                        "type": "text",
                        "required": true
                    },
                    {
                        "id": "q_like",
                        "type": "text"
                    }
                ]
            }
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/static/examples/bigform/instrument.json
{
  "id": "urn:demo-instrument",
  "version": "1.0",

  "title": "Demonstration Instrument",
  "description": "An instrument that demonstrates all the field types.",

  "types": {
    "fruit": {
      "base": "enumerationSet",
      "enumerations": {
        "apple": {},
        "banana": {},
        "orange": {},
        "watermelon": {}
      }
    },

    "colors": {
      "base": "enumeration",
      "enumerations": {
        "red": {},
        "blue": {},
        "green": {}
      }
    }
  },

  "record": [
    {
      "id": "q_float1",
      "type": "float"
    },
    {
      "id": "q_float2",
      "type": "float"
    },
    {
      "id": "q_float3",
      "type": "float"
    },
    {
      "id": "q_integer1",
      "type": "integer"
    },
    {
      "id": "q_integer2",
      "type": "integer"
    },
    {
      "id": "q_integer3",
      "type": "integer"
    },
    {
      "id": "q_text1",
      "type": "text"
    },
    {
      "id": "q_text2",
      "type": "text"
    },
    {
      "id": "q_text3",
      "type": "text"
    },
    {
      "id": "q_text4",
      "type": "text"
    },
    {
      "id": "q_text5",
      "type": "text"
    },
    {
      "id": "q_text6",
      "type": "text"
    },
    {
      "id": "q_text7",
      "type": "text",
      "explanation": "required",
      "annotation": "required"
    },
    {
      "id": "q_text8",
      "type": "text",
      "explanation": "required",
      "annotation": "optional"
    },
    {
      "id": "q_text9",
      "type": "text",
      "explanation": "optional",
      "annotation": "required"
    },
    {
      "id": "q_text10",
      "type": "text",
      "explanation": "optional",
      "annotation": "optional"
    },
    {
      "id": "q_text11",
      "type": "text"
    },
    {
      "id": "q_text12",
      "type": "text"
    },
    {
      "id": "q_text13",
      "type": "text"
    },
    {
      "id": "q_enumeration1",
      "type": "colors"
    },
    {
      "id": "q_enumeration2",
      "type": "colors"
    },
    {
      "id": "q_enumeration3",
      "type": "colors"
    },
    {
      "id": "q_enumerationset1",
      "type": "fruit"
    },
    {
      "id": "q_boolean1",
      "type": "boolean"
    },
    {
      "id": "q_boolean2",
      "type": "boolean"
    },
    {
      "id": "q_boolean3",
      "type": "boolean"
    },
    {
      "id": "q_boolean4",
      "type": "boolean"
    },
    {
      "id": "q_boolean5",
      "type": "boolean"
    },
    {
      "id": "q_boolean6",
      "type": "boolean"
    },
    {
      "id": "q_boolean7",
      "type": "boolean"
    },
    {
      "id": "q_boolean8",
      "type": "boolean"
    },
    {
      "id": "q_date1",
      "type": "date"
    },
    {
      "id": "q_time1",
      "type": "time"
    },
    {
      "id": "q_datetime1",
      "type": "dateTime"
    },
    {
      "id": "q_recordlist1",
      "type": {
        "base": "recordList",
        "record": [
          {
            "id": "q_rec_integer",
            "type": "integer"
          },
          {
            "id": "q_rec_text",
            "type": "text"
          },
          {
            "id": "q_rec_enumeration",
            "type": "colors"
          }
        ]
      }
    },
    {
      "id": "q_matrix1",
      "type": {
        "base": "matrix",
        "columns": [
          {
            "id": "q_mtx_integer",
            "type": "integer"
          },
          {
            "id": "q_mtx_text",
            "type": "text"
          },
          {
            "id": "q_mtx_enumeration",
            "type": "colors"
          }
        ],
        "rows": [
          {
            "id": "first"
          },
          {
            "id": "second"
          }
        ]
      }
    },
    {
      "id": "q_calculated",
      "type": "text"
    }
  ]
}
