=== Ghostrecon88/baseline-codebase/src/rex.forms/src/rex/forms/schemas/form.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "id": "http://rexdb.com/form/0.4.0#",
    "title": "Form Configuration Definition",

    "definitions": {
        "localizedStringType": {
            "type": "object",

            "patternProperties": {
                "^[a-z]{2}(-[a-zA-Z]{2})?$": {
                    "type": "string"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "instrumentType": {
            "type": "object",

            "properties": {
                "id": {
                    "type": "string",
                    "format": "uri"
                },

                "version": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+$"
                }
            },

            "required": [
                "id",
                "version"
            ],

            "additionalProperties": false
        },

        "expressionType": {
            "type": "string"
        },

        "widgetType": {
            "type": "object",

            "properties": {
                "type": {
                    "type": "string",
                    "minLength": 1
                },

                "options": {
                    "type": "object",
                    "minProperties": 1
                }
            },

            "required": [
                "type"
            ],

            "additionalProperties": false
        },

        "descriptorType": {
            "type": "object",

            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
                },

                "text": {
                    "$ref": "#/definitions/localizedStringType"
                },

                "help": {
                    "$ref": "#/definitions/localizedStringType"
                }
            },

            "required": [
                "id",
                "text"
            ],

            "additionalProperties": false
        },

        "descriptorListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/descriptorType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "targetListType": {
            "type": "array",

            "items": {
                "type": "string",
                "pattern": "^([a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9])(\\.([a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]))*$"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "eventType": {
            "type": "object",

            "properties": {
                "trigger": {
                    "$ref": "#/definitions/expressionType"
                },

                "action": {
                    "enum": [
                        "hide",
                        "disable",
                        "hideEnumeration",
                        "fail",
                        "calculate"
                    ]
                },

                "targets": {
                    "$ref": "#/definitions/targetListType"
                },

                "options": {
                    "type": "object",
                    "minProperties": 1
                }
            },

            "required": [
                "trigger",
                "action"
            ],

            "additionalProperties": false
        },

        "eventListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/eventType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "questionElementType": {
            "type": "object",

            "properties": {
                "fieldId": {
                    "type": "string",
                    "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
                },

                "text": {
                    "$ref": "#/definitions/localizedStringType"
                },

                "help": {
                    "$ref": "#/definitions/localizedStringType"
                },

                "error": {
                    "$ref": "#/definitions/localizedStringType"
                },

                "widget": {
                    "$ref": "#/definitions/widgetType"
                },

                "enumerations": {
                    "$ref": "#/definitions/descriptorListType"
                },

                "questions": {
                    "$ref": "#/definitions/questionListType"
                },

                "rows": {
                    "$ref": "#/definitions/descriptorListType"
                },

                "events": {
                    "$ref": "#/definitions/eventListType"
                }
            },

            "required": [
                "fieldId"
            ],

            "additionalProperties": false
        },

        "questionListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/questionElementType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "textElementType": {
            "type": "object",

            "properties": {
                "text": {
                    "$ref": "#/definitions/localizedStringType"
                }
            },

            "required": [
                "text"
            ],

            "additionalProperties": false
        },

        "tagListType": {
            "type": "array",

            "items": {
                "type": "string",
                "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "elementType": {
            "type": "object",

            "properties": {
                "type": {
                    "enum": [
                        "question",
                        "header",
                        "text",
                        "divider"
                    ]
                },

                "options": {
                    "anyOf": [
                        { "$ref": "#/definitions/questionElementType" },
                        { "$ref": "#/definitions/textElementType" }
                    ]
                },

                "tags": {
                    "$ref": "#/definitions/tagListType"
                }
            },

            "required": [
                "type"
            ],

            "additionalProperties": false
        },

        "elementListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/elementType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "pageType": {
            "type": "object",

            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
                },

                "elements": {
                    "$ref": "#/definitions/elementListType"
                }
            },

            "required": [
                "id",
                "elements"
            ],

            "additionalProperties": false
        },

        "pageListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/pageType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "unpromptedType": {
            "type": "object",

            "properties": {
                "action": {
                    "enum": [
                        "calculate"
                    ]
                },

                "options": {
                    "type": "object",
                    "minProperties": 1
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "unpromptedCollectionType": {
            "type": "object",

            "patternProperties": {
                "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$": {
                    "$ref": "#/definitions/unpromptedType"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "parameterType": {
            "type": "object",

            "properties": {
                "type": {
                    "enum": [
                        "numeric",
                        "text",
                        "boolean"
                    ]
                }
            },

            "required": [
                "type"
            ],

            "additionalProperties": false
        },

        "parameterCollectionType": {
            "type": "object",

            "patternProperties": {
                "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$": {
                    "$ref": "#/definitions/parameterType"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        }
    },

    "type": "object",

    "properties": {
        "instrument": {
            "$ref": "#/definitions/instrumentType"
        },

        "defaultLocalization": {
            "type": "string",
            "pattern": "^[a-z]{2}(-[a-zA-Z]{2})?$"
        },

        "title": {
            "$ref": "#/definitions/localizedStringType"
        },

        "tags": {
            "$ref": "#/definitions/tagListType"
        },

        "pages": {
            "$ref": "#/definitions/pageListType"
        },

        "unprompted": {
            "$ref": "#/definitions/unpromptedCollectionType"
        },

        "parameters": {
            "$ref": "#/definitions/parameterCollectionType"
        }
    },

    "required": [
        "instrument",
        "defaultLocalization",
        "pages"
    ],

    "additionalProperties": false
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/static/js/example/specs/forms/text_rendering/form.json
{
  "instrument": {
    "id": "urn:text-rendering",
    "version": "1.0"
  },
  "defaultLocalization": "en",
  "title": {
    "en": "An Exercise in Various Text Rendering Options"
  },
  "parameters": {
    "a_string": {
      "type": "text"
    },
    "a_number": {
      "type": "numeric"
    },
    "a_boolean": {
      "type": "boolean"
    }
  },
  "pages": [
    {
      "id": "questions",
      "elements": [
        {
          "type": "header",
          "options": {
            "text": {
              "en": "Question Text, Help, and Errors"
            }
          }
        },
        {
          "type": "question",
          "options": {
            "fieldId": "q1",
            "text": {
              "en": "This question has help text."
            },
            "help": {
              "en": "This is helpful text."
            }
          }
        },
        {
          "type": "question",
          "options": {
            "fieldId": "q2",
            "text": {
              "en": "This question has error text."
            },
            "error": {
              "en": "You done messed up now."
            }
          }
        },
        {
          "type": "question",
          "options": {
            "fieldId": "q3",
            "text": {
              "en": "This question has both help and error text."
            },
            "help": {
              "en": "You should enter an integer (like <<Parameter a_number>>)."
            },
            "error": {
              "en": "You done messed up now."
            }
          }
        },
        {
          "type": "question",
          "options": {
            "fieldId": "q4",
            "text": {
              "en": "This question has both **help** and **error** text the contains //markup//."
            },
            "help": {
              "en": "This is **//helpful text//**."
            },
            "error": {
              "en": "You done **messed up** now."
            }
          }
        },
        {
          "type": "question",
          "options": {
            "fieldId": "q5",
            "text": {
              "en": "It's <<Parameter a_boolean>>, enumeration choices can have markup and help, as well."
            },
            "enumerations": [
              {
                "id": "foo",
                "text": {
                  "en": "The //Foo// Description"
                }
              },
              {
                "id": "bar",
                "text": {
                  "en": "A Bar"
                },
                "help": {
                  "en": "This is helpful text."
                }
              },
              {
                "id": "baz",
                "text": {
                  "en": "Some **Bazzy** Thing"
                },
                "help": {
                  "en": "This is **more** //helpful// text."
                }
              }
            ]
          }
        },
        {
          "type": "question",
          "options": {
            "fieldId": "q5-2",
            "text": {
              "en": "It's <<Parameter a_boolean>>, enumeration choices can have markup and help, as well."
            },
            "enumerations": [
              {
                "id": "red",
                "text": {
                  "en": "The //Red// Description"
                }
              },
              {
                "id": "blue",
                "text": {
                  "en": "A Blue"
                },
                "help": {
                  "en": "This is helpful text."
                }
              },
              {
                "id": "green",
                "text": {
                  "en": "Some **Greeny** Thing"
                },
                "help": {
                  "en": "This is **more** //helpful// text."
                }
              }
            ]
          }
        },
        {
          "type": "question",
          "options": {
            "fieldId": "q6",
            "text": {
              "en": "Matrix rows can have help text, and columns can have help and error text."
            },
            "rows": [
              {
                "id": "row1",
                "text": {
                  "en": "First Row"
                },
                "help": {
                  "en": "Some helpful **hints**."
                }
              },
              {
                "id": "row2",
                "text": {
                  "en": "Second Row"
                }
              }
            ],
            "questions": [
              {
                "fieldId": "col1",
                "text": {
                  "en": "Enter some text."
                },
                "help": {
                  "en": "Any text will do."
                }
              },
              {
                "fieldId": "col2",
                "text": {
                  "en": "Pick a number."
                },
                "error": {
                  "en": "You //keep// doing things wrong."
                }
              }
            ]
          }
        }
      ]
    },
    {
      "id": "non_questions",
      "elements": [
        {
          "type": "header",
          "options": {
            "text": {
              "en": "[[http://www.google.com|Headers]] Can Have //Markup//"
            }
          }
        },
        {
          "type": "text",
          "options": {
            "text": {
              "en": "The a_string parameter contains \"<<Parameter a_string>>\""
            }
          }
        },
        {
          "type": "divider"
        },
        {
          "type": "text",
          "options": {
            "text": {
              "en": "[[http://en.wikipedia.org/wiki/Lorem_ipsum|Lorem ipsum]] dolor\nsit amet, consectetur adipiscing elit.  Donec dignissim felis\nlectus, at aliquam tortor vulputate nec. Nullam dui dui, rutrum\nut enim quis, fringilla rutrum nulla. Proin sem odio, posuere ac\nsodales at, fermentum ut nunc. Nam sodales mi quis felis accumsan\negestas. Etiam in turpis non lacus posuere interdum. Vivamus ut\nenim lobortis, congue sapien in, egestas metus. Vestibulum id\narcu non tellus convallis suscipit nec quis risus. Cras ornare\nornare mattis. Phasellus malesuada purus elit, eget cursus orci\ndictum at. Vivamus vitae euismod risus.\n\n# Phasellus vehicula sem massa, nec molestie dolor tristique et.\n# Praesent nec tempor justo, ac dapibus justo.\n## Morbi sollicitudin viverra hendrerit.\n\nPellentesque euismod facilisis leo at tempus.  **Mauris a ipsum\ntempor**, porta tellus vel, ultrices velit.  Nulla facilisi.\nQuisque id facilisis ante, ac egestas urna.  Nullam pretium\nsagittis nunc eu congue. Proin quis arcu eget tortor bibendum\nsemper. Sed sit amet cursus risus. Morbi dignissim neque nec\nviverra laoreet. Duis ultrices lorem sit amet risus egestas, eget\nsagittis eros suscipit. //**Vestibulum**// sed orci eget dui\nrhoncus vestibulum sed placerat ante. Vivamus ornare elit non\nligula vehicula dictum consequat vitae nisl. Cras sagittis\niaculis eros, lobortis consequat nulla mollis id.  Suspendisse\nsemper lectus posuere vehicula pulvinar. Vivamus quis convallis\nsapien, in iaculis mi. //Fusce lobortis//, ipsum sit amet\nconsectetur semper, purus magna ultrices risus, et malesuada nisi\nipsum rutrum libero.\n\n* Donec semper elit a ligula egestas, at congue ante euismod.\n* Nam facilisis quam elementum, congue enim et, scelerisque arcu.\n** Morbi a luctus tortor.\n* Pellentesque pellentesque, risus in tincidunt elementum, felis ipsum euismod sapien, eget vestibulum sapien massa ut turpis.\n\n===Sed lacus lectus, scelerisque ut turpis at, tincidunt vehicula massa.===\n\nVivamus adipiscing nec tortor id posuere. Quisque et lectus non\ndolor porta iaculis. Proin pellentesque mattis dictum. Nam ac\nnisl arcu. Nunc felis elit, dictum vel massa sed, viverra ornare\ndiam.\n\n|=Header1 |=Header2 |\n|this     |is       |\n|a        |table    |\n"
            }
          }
        }
      ]
    }
  ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/static/examples/recordlist/form.json
{
    "instrument": {
        "id": "urn:instrument",
        "version": "1.0"
    },
    "defaultLocalization": "en",
    "title": {
      "en": "Form which demonstrates recordList widget"
    },
    "pages": [
        {
            "id": "page1",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_list",
                        "text": {
                            "en": "List all your favourite things"
                        },
                        "error": {
                            "en": "At least two elements should be present"
                        },
                        "questions": [
                            {
                                "fieldId": "q_thing",
                                "text": {
                                    "en": "What do you like?"
                                }
                            },
                            {
                                "fieldId": "q_like",
                                "text": {
                                    "en": "How much do you like it?"
                                }
                            }
                        ],
                        "events": [
                            {
                                "action": "fail",
                                "trigger": "if(q_list,q_list.value.length<2,true())"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/static/examples/study_demo/form.json
{
    "instrument": {
        "id": "urn:rex_instrument_study_demo:sample",
        "version": "1.1"
    },
    "title": {
      "en": "Study demo form"
    },
    "defaultLocalization": "en",
    "pages": [
        {
            "id": "page1",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_foobar",
                        "text": {
                            "en": "How many years old are you?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_datetime",
                        "text": {
                            "en": "What is your favorite datetime?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_enum",
                        "text": {
                            "en": "Pick a color:"
                        },
                        "enumerations": [
                            {
                                "id": "blue",
                                "text": { "en": "Blue!" }
                            },
                            {
                                "id": "red",
                                "text": {"en": "Red?"},
                                "help": {"en": "It's red, dummy."}
                            }
                        ],
                        "widget": {
                            "type": "radioGroup"
                        }
                    }
                }
            ]
        },
        {
            "id": "page2",
            "elements": [
                {
                    "type": "text",
                    "options": {
                        "text": {
                            "en": "Lectus laoreet lobortis urna proin, volutpat sem tempus torquent eros ridiculus congue, cursus ullamcorper hac habitasse, metus aliquam eros ridiculus. Venenatis viverra velit placerat tempus neque inceptos, mi pede scelerisque eu dapibus, eleifend et luctus odio rutrum augue, hendrerit vitae. Suspendisse sit velit aliquam laoreet velit, et praesent at congue, semper venenatis porttitor auctor sociis egestas nec, sapien imperdiet arcu pede nascetur. Dui faucibus eu hendrerit accumsan, malesuada tempus curabitur facilisis, dis accumsan mollis nulla quam mattis dictum, massa purus ipsum. Adipiscing.",
                            "fr": "This is some French text."
                        }
                    }
                },
               {
                    "type": "question",
                    "options": {
                        "fieldId": "q_date",
                        "text": {
                            "en": "What is your favorite date?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_time",
                        "text": {
                            "en": "What is your favorite time?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_enumset",
                        "text": {
                            "en": "Pick your 2 favorite shapes:"
                        },
                        "enumerations": [
                            {
                                "id": "circle",
                                "text": { "en": "Circle" }
                            },
                            {
                                "id": "triangle",
                                "text": { "en": "Triangle" }
                            },
                            {
                                "id": "square",
                                "text": { "en": "SQUARES!@!" }
                            },
                            {
                                "id": "octogon",
                                "text": {"en": "Doctor Octogon"}
                            }
                        ],
                        "widget": {
                            "type": "checkGroup"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_int",
                        "text": {
                            "en": "What is your favorite integer?"
                        },
                        "widget": {
                            "type": "inputText",
                            "options": {
                                "width": "small"
                            }
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_float",
                        "text": {
                            "en": "What is your favorite float?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_bool",
                        "text": {
                            "en": "Are you awesome?"
                        }
                    }
                }
            ]
        },
        {
            "id": "page3",
            "elements": [
                {
                    "type": "text",
                    "options": {
                        "text": {
                            "en": "Hello there!"
                        }
                    }
                },
                {
                    "type": "divider"
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_text",
                        "widget": {
                            "type": "textArea",
                            "options": {
                                "width": "small",
                                "height": "small"
                            }
                        },
                        "text": {
                            "en": "What is your favorite word?"
                        }
                    }
                }
            ]
        }
    ]
}
