=== Ghostrecon88/baseline-codebase/src/rex.forms/src/rex/forms/schemas/form.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "id": "http://rexdb.com/form/0.4.0#",
    "title": "Form Configuration Definition",

    "definitions": {
        "localizedStringType": {
            "type": "object",

            "patternProperties": {
                "^[a-z]{2}(-[a-zA-Z]{2})?$": {
                    "type": "string"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "instrumentType": {
            "type": "object",

            "properties": {
                "id": {
                    "type": "string",
                    "format": "uri"
                },

                "version": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+$"
                }
            },

            "required": [
                "id",
                "version"
            ],

            "additionalProperties": false
        },

        "expressionType": {
            "type": "string"
        },

        "widgetType": {
            "type": "object",

            "properties": {
                "type": {
                    "type": "string",
                    "minLength": 1
                },

                "options": {
                    "type": "object",
                    "minProperties": 1
                }
            },

            "required": [
                "type"
            ],

            "additionalProperties": false
        },

        "descriptorType": {
            "type": "object",

            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
                },

                "text": {
                    "$ref": "#/definitions/localizedStringType"
                },

                "help": {
                    "$ref": "#/definitions/localizedStringType"
                }
            },

            "required": [
                "id",
                "text"
            ],

            "additionalProperties": false
        },

        "descriptorListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/descriptorType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "targetListType": {
            "type": "array",

            "items": {
                "type": "string",
                "pattern": "^([a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9])(\\.([a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]))*$"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "eventType": {
            "type": "object",

            "properties": {
                "trigger": {
                    "$ref": "#/definitions/expressionType"
                },

                "action": {
                    "enum": [
                        "hide",
                        "disable",
                        "hideEnumeration",
                        "fail",
                        "calculate"
                    ]
                },

                "targets": {
                    "$ref": "#/definitions/targetListType"
                },

                "options": {
                    "type": "object",
                    "minProperties": 1
                }
            },

            "required": [
                "trigger",
                "action"
            ],

            "additionalProperties": false
        },

        "eventListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/eventType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "questionElementType": {
            "type": "object",

            "properties": {
                "fieldId": {
                    "type": "string",
                    "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
                },

                "text": {
                    "$ref": "#/definitions/localizedStringType"
                },

                "help": {
                    "$ref": "#/definitions/localizedStringType"
                },

                "error": {
                    "$ref": "#/definitions/localizedStringType"
                },

                "widget": {
                    "$ref": "#/definitions/widgetType"
                },

                "enumerations": {
                    "$ref": "#/definitions/descriptorListType"
                },

                "questions": {
                    "$ref": "#/definitions/questionListType"
                },

                "rows": {
                    "$ref": "#/definitions/descriptorListType"
                },

                "events": {
                    "$ref": "#/definitions/eventListType"
                }
            },

            "required": [
                "fieldId"
            ],

            "additionalProperties": false
        },

        "questionListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/questionElementType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "textElementType": {
            "type": "object",

            "properties": {
                "text": {
                    "$ref": "#/definitions/localizedStringType"
                }
            },

            "required": [
                "text"
            ],

            "additionalProperties": false
        },

        "tagListType": {
            "type": "array",

            "items": {
                "type": "string",
                "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "elementType": {
            "type": "object",

            "properties": {
                "type": {
                    "enum": [
                        "question",
                        "header",
                        "text",
                        "divider"
                    ]
                },

                "options": {
                    "anyOf": [
                        { "$ref": "#/definitions/questionElementType" },
                        { "$ref": "#/definitions/textElementType" }
                    ]
                },

                "tags": {
                    "$ref": "#/definitions/tagListType"
                }
            },

            "required": [
                "type"
            ],

            "additionalProperties": false
        },

        "elementListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/elementType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "pageType": {
            "type": "object",

            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$"
                },

                "elements": {
                    "$ref": "#/definitions/elementListType"
                }
            },

            "required": [
                "id",
                "elements"
            ],

            "additionalProperties": false
        },

        "pageListType": {
            "type": "array",

            "items": {
                "$ref": "#/definitions/pageType"
            },

            "minItems": 1,

            "additionalItems": false
        },

        "unpromptedType": {
            "type": "object",

            "properties": {
                "action": {
                    "enum": [
                        "calculate"
                    ]
                },

                "options": {
                    "type": "object",
                    "minProperties": 1
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "unpromptedCollectionType": {
            "type": "object",

            "patternProperties": {
                "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$": {
                    "$ref": "#/definitions/unpromptedType"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        },

        "parameterType": {
            "type": "object",

            "properties": {
                "type": {
                    "enum": [
                        "numeric",
                        "text",
                        "boolean"
                    ]
                }
            },

            "required": [
                "type"
            ],

            "additionalProperties": false
        },

        "parameterCollectionType": {
            "type": "object",

            "patternProperties": {
                "^[a-z](?:[a-z0-9]|[_-](?![_-]))*[a-z0-9]$": {
                    "$ref": "#/definitions/parameterType"
                }
            },

            "minProperties": 1,

            "additionalProperties": false
        }
    },

    "type": "object",

    "properties": {
        "instrument": {
            "$ref": "#/definitions/instrumentType"
        },

        "defaultLocalization": {
            "type": "string",
            "pattern": "^[a-z]{2}(-[a-zA-Z]{2})?$"
        },

        "title": {
            "$ref": "#/definitions/localizedStringType"
        },

        "tags": {
            "$ref": "#/definitions/tagListType"
        },

        "pages": {
            "$ref": "#/definitions/pageListType"
        },

        "unprompted": {
            "$ref": "#/definitions/unpromptedCollectionType"
        },

        "parameters": {
            "$ref": "#/definitions/parameterCollectionType"
        }
    },

    "required": [
        "instrument",
        "defaultLocalization",
        "pages"
    ],

    "additionalProperties": false
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/static/examples/calculateelement/form.json
{
    "instrument": {
        "id": "urn:test-instrument",
        "version": "1.1"
    },
    "defaultLocalization": "en",
    "title": {
        "en": "Form with calculated fields"
    },
    "pages": [
        {
            "id": "page1",
            "elements": [
                {
                    "type": "text",
                    "options": {
                        "text": {
                            "en": "Note that this form has two fields with calculated values. But only one of those is rendered."
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_name",
                        "text": {
                            "en": "What's your name?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_age",
                        "text": {
                            "en": "How old are you?"
                        },
                        "help": {
                            "en": "If you are more than 18 years old you should answer for more questions!"
                        },
                        "events": [
                            {
                                "action": "calculate",
                                "trigger": "if(q_age<18,'Moscow',null())",
                                "targets": ["q_city"]
                            },
                            {
                                "action": "calculate",
                                "trigger": "if(q_age<18,'Russia',null())",
                                "targets": ["q_country"]
                            }
                        ]
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_country",
                        "text": {
                            "en": "Country?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_place",
                        "text": {
                            "en": "Place?"
                        }
                    }
                }
            ]
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/static/examples/disableelement/form.json
{
    "instrument": {
        "id": "urn:test-instrument",
        "version": "1.1"
    },
    "defaultLocalization": "en",
    "title": {
        "en": "Form with triggers for disabled fields"
    },
    "pages": [
        {
            "id": "page1",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_name",
                        "text": {
                            "en": "What's your name?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_age",
                        "text": {
                            "en": "How old are you?"
                        },
                        "help": {
                            "en": "If you are more than 18 years old you should answer for more questions!"
                        },
                        "events": [
                            {
                                "action": "disable",
                                "trigger": "q_age<18",
                                "targets": ["q_city"]
                            },
                            {
                                "action": "disable",
                                "trigger": "q_age<18",
                                "targets": ["q_country"]
                            }
                        ]
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_city",
                        "text": {
                            "en": "City?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_country",
                        "text": {
                            "en": "Country?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_place",
                        "text": {
                            "en": "Place?"
                        }
                    }
                }
            ]
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/test/forms/title_unicode.json
{
    "instrument": {
        "id": "urn:test-instrument",
        "version": "1.1"
    },
    "defaultLocalization": "en",
    "title": {
      "en": "Hello",
      "ar": "مرحبا"
    },
    "pages": [
        {
            "id": "page1",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_fake",
                        "text": {
                            "en": "How do you feel today?"
                        }
                    }
                }
            ]
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/rex.forms_demo/static/examples/simple/form.json
{
    "instrument": {
        "id": "urn:test-instrument",
        "version": "1.1"
    },
    "defaultLocalization": "en",
    "title": {
        "en": "Simple form example"
    },
    "pages": [
        {
            "id": "page1",
            "elements": [
                {
                    "type": "text",
                    "options": {
                        "text": {
                            "en": "This //is// some text with **markup**.\n\nLet's do some lists:\n* item 1\n* item 2"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_name",
                        "text": {
                            "en": "What's your name?"
                        },
                        "help": {
                            "en": "Enter your name (you can provide annotation)"
                        }
                    }
                },
                {
                    "type": "divider",
                    "options": {}
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_country",
                        "text": {
                            "en": "Country?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_color",
                        "text": {
                            "en": "What's your favourite color?"
                        }
                    }
                }
            ]
        },
        {
            "id": "page2",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_city",
                        "text": {
                            "en": "City?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_age",
                        "text": {
                            "en": "How old are you?"
                        },
                        "help": {
                            "en": "You should provide annotation"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_car",
                        "text": {
                            "en": "Car?"
                        }
                    }
                }
            ]
        },
        {
            "id": "page3",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_place",
                        "text": {
                            "en": "Place?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_something",
                        "text": {
                            "en": "Some thing?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_anotherthing",
                        "text": {
                            "en": "Another thing?"
                        }
                    }
                }
            ]
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/static/examples/hidepage/form.json
{
    "instrument": {
        "id": "urn:test-instrument",
        "version": "1.1"
    },
    "defaultLocalization": "en",
    "title": {
        "en": "Form with triggers for hidden pages"
    },
    "pages": [
        {
            "id": "page1",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_name",
                        "text": {
                            "en": "What's your name?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_age",
                        "text": {
                            "en": "How old are you?"
                        },
                        "help": {
                            "en": "If you are more than 18 years old you should answer for more questions!"
                        },
                        "events": [
                            {
                                "action": "hide",
                                "trigger": "q_age<18",
                                "targets": ["page2"]
                            }
                        ]
                    }
                }
            ]
        },
        {
            "id": "page2",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_city",
                        "text": {
                            "en": "City?"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_country",
                        "text": {
                            "en": "Country?"
                        }
                    }
                }
            ]
        },
        {
            "id": "page3",
            "elements": [
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_place",
                        "text": {
                            "en": "Place?"
                        }
                    }
                }
            ]
        }
    ]
}

=== Ghostrecon88/baseline-codebase/src/rex.forms/demo/static/examples/matrix/form.json
{
    "instrument": {
        "id": "urn:instrument",
        "version": "1.0"
    },
    "title": {
      "en": "Form which demonstrates matrix widget"
    },
    "defaultLocalization": "en",
    "pages": [
        {
            "id": "page1",
            "elements": [
                {
                    "type": "header",
                    "options": {
                        "text": {
                            "en": "Header"
                        }
                    }
                },
                {
                    "type": "text",
                    "options": {
                        "text": {
                            "en": "Text"
                        }
                    }
                },
                {
                    "type": "question",
                    "options": {
                        "fieldId": "q_matrix",
                        "text": {
                            "en": "Now try to fill every question in the matrix"
                        },
                        "help": {
                            "en": "Enter questions for each row"
                        },
                        "questions": [
                            {
                                "fieldId": "q_blah",
                                "text": {
                                    "en": "Blah?"
                                },
                                "help": {
                                    "en": "Enter blah, required"
                                }
                            },
                            {
                                "fieldId": "q_foobar",
                                "text": {
                                    "en": "Foobar?"
                                }
                            }
                        ],
                        "rows": [
                            {
                                "id": "somerow",
                                "text": {"en": "Some Row"}
                            },
                            {
                                "id": "anotherrow",
                                "text": {"en": "Another Row"},
                                "help": {"en": "Enter values for another row"}
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
